CREATE DATABASE VFSHOPPER1
USE VFSHOPPER1


SELECT * FROM PERFIL
SELECT * FROM CATEGORIA
SELECT * FROM STATUSS
SELECT * FROM USUARIO
SELECT * FROM COMPRAS
SELECT * FROM ORCAMENTO

/*delete from STATUSS WHERE COD_STATUS = 8*/

CREATE TABLE PERFIL
(
    COD_PERFIL INT IDENTITY(1,1),
    NOME VARCHAR(100) NOT NULL,
    PRIMARY KEY(COD_PERFIL)
)

CREATE TABLE CATEGORIA
(
	COD_CATEGORIA INT IDENTITY (1,1),
	NOME VARCHAR(150) NOT NULL,
    PRIMARY KEY(COD_CATEGORIA)
)

CREATE TABLE STATUSS
(	
	COD_STATUS INT IDENTITY (1,1),
	NOME VARCHAR (150) NOT NULL,
	PRIMARY KEY (COD_STATUS)
)


CREATE TABLE USUARIO
(
	COD_USUARIO INT IDENTITY (1,1),
	COD_PERFIL INT NOT NULL,
	NOME VARCHAR (150) NOT NULL,
	EMAIL VARCHAR (300) NOT NULL UNIQUE,
	PRIMARY KEY (COD_USUARIO),
	FOREIGN KEY (COD_PERFIL) REFERENCES PERFIL (COD_PERFIL)
)

CREATE TABLE COMPRAS
(
	COD_COMPRAS INT IDENTITY (1,1),
	TITULO VARCHAR (100) NOT NULL,
	DESCRICAO VARCHAR (500) NOT NULL,
	COD_STATUS INT NOT NULL  DEFAULT 1,
	COD_CATEGORIA INT,
	COD_USUARIO INT,
	DATA_ABERTURA DATETIME DEFAULT GETDATE(),
	DATA_FINALIZACAO DATETIME DEFAULT ('1900-01-01T00:00:00.000'),
	PRIMARY KEY (COD_COMPRAS),
	FOREIGN KEY (COD_STATUS) REFERENCES STATUSS (COD_STATUS),
	FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA (COD_CATEGORIA),
	FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO)
)

CREATE TABLE ORCAMENTO
(
	COD_ORCAMENTO INT IDENTITY (1,1),
	COD_COMPRAS INT,
	NOME VARCHAR (100) NOT NULL,
	LINK VARCHAR (300) NOT NULL,
	OBSERVACAO VARCHAR(350),
	PRIMARY KEY (COD_ORCAMENTO),
	FOREIGN KEY (COD_COMPRAS)
		REFERENCES COMPRAS (COD_COMPRAS)
)

INSERT INTO STATUSS (NOME)
VALUES
    ('Aguardando aprovação'),
    ('Aprovado'),
    ('Reprovado'),
	('Finalizado')

INSERT INTO CATEGORIA(NOME)
VALUES
	('Periféricos'),
	('Hardware'),
	('Software')


INSERT INTO PERFIL (NOME)
VALUES
	('Admin'),
	('Gerente'),
	('Analista de Compras')


INSERT INTO USUARIO (NOME, EMAIL, COD_PERFIL)
VALUES
	('Pedro', 'ped.321@hotmail.com', 1),
	('Grazielle', 'grazi.lemoss@gmail.com',2),
	('João', 'joao.schmidt@viaflow.com.br', 3)

UPDATE COMPRAS 
	SET COD_STATUS = 2
	WHERE COD_COMPRAS IN(6,5,3)